### ISSUE TITLE
App get restart 

### ISSUE THREAD

**Issue by Austin880** [prateek-chaubey/YTPro#19]
while app playing in the background, app get restart after 3 to 4min

**Comment by prateek-chaubey** [comment]
Seems like we are on the same page [ToDo](https://github.com/prateek-chaubey/YTPro?tab=readme-ov-file#todo) .
Sadly I am also waiting for myself to add a perfect background player.


Basically the issue is that app gets killed by Android process after it's in background for long period of time.
I am thinking to implement a audio player specifically for the background player.
If you have any ideas or code you can contribute into this.

**Comment by prateek-chaubey** [comment]
Updated the app in the latest release [v3.4](https://github.com/prateek-chaubey/YTPro/releases/tag/v3.4)
